# Generated by Django 3.2.6 on 2021-08-23 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.IntegerField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=8)),
                ('sex', models.BooleanField()),
                ('aihao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.logininfo')),
            ],
        ),
    ]
